### ISSUE TITLE
Typo on Nominator Page

### ISSUE THREAD

**Issue by RossLloyd** [reef-defi/reef-docs#4]
Update Text on Page: https://docs.reef.finance/docs/governance/nominators/

![image](https://user-images.githubusercontent.com/25029366/113855385-df786f80-9797-11eb-89db-4a1153233394.png)

should read...

Become a nominator
After careful consideration of the best Validator candidates - based on their technical abilities and community contributions - we are ready to vote.

**Comment by Netherdrake** [comment]
Fixed, thanks
