### ISSUE TITLE
Typo on Networks Page

### ISSUE THREAD

**Issue by RossLloyd** [reef-defi/reef-docs#5]
Update Text on Page: https://docs.reef.finance/docs/developers/networks/

![image](https://user-images.githubusercontent.com/25029366/113855730-48f87e00-9798-11eb-9ed6-af1c258611e3.png)

should read... (Under Start a RPC)

The last thing we need is the chain_spec.json file. Compiling WASM is not deterministic, yet we want to have matching genesis.

**Comment by Netherdrake** [comment]
Fixed it
